### ISSUE TITLE
When will all the codes be released? 

### ISSUE THREAD

**Issue by ShileiCao** [kyegomez/Aurora#1]
When will all the codes be released? Thanks a lot

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/Aurora/issues/1">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/Aurora/issues/1/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/Aurora/issues/1/pledge.svg">
</picture>
</a>

**Comment by qwe3588** [comment]
I'd like to know that too!

**Comment by kyegomez** [comment]
@qwe3588 @ShileiCao havent worked on this paper yet if you want to help with it please join the agora discord group
